spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017,localhost:27018,localhost:27019
      database: test
      authentication-database: admin
      transactionEnabled: true
      #field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      #驼峰转下划线
      property-naming-strategy: SNAKE_CASE
      transaction-enable: true